# Notebook to get data from API

We'll collect data using the [swapi API](https://swapi.dev/) using the python [swapi library](https://github.com/phalt/swapi-python) and store the outputs in csv files for exploration and analysis.

## Setup

In [24]:
import pandas as pd
import swapi
import numpy as np
import matplotlib.pyplot as plt
import requests
import json
import os

In [25]:
# change directory
os.chdir("..")

# Exploring API

https://swapi-python.readthedocs.io/en/latest/models.html#multiple-collection-model

In [37]:
films = swapi.get_all("films")
planets = swapi.get_all("planets")
planets

In [80]:
planet = swapi.get_planet(1)
planet.name

'Tatooine'

## Get films

In [3]:
# get films from swapi
films = swapi.get_all("films")

#setup empty dictionary
films_df = {"title": [],
            "episode_id":[] ,
            "opening_crawl":[] ,
            "director": [],
            "producer":[],
            "release_date":[],
            "species":[] ,
            "starships":[] ,
            "vehicles":[] ,
            "characters":[] ,
            "planets":[] ,
            "url":[] ,
            "created":[] ,
            "edited":[]}

#get data and store in dictionary
for v in films.iter():
    films_df[list(films_df)[0]].append(v.title)
    films_df[list(films_df)[1]].append(v.episode_id)
    films_df[list(films_df)[2]].append(v.opening_crawl)
    films_df[list(films_df)[3]].append(v.director)
    films_df[list(films_df)[4]].append(v.producer)
    films_df[list(films_df)[5]].append(v.release_date)
    films_df[list(films_df)[6]].append(v.species)
    films_df[list(films_df)[7]].append(v.starships)
    films_df[list(films_df)[8]].append(v.vehicles)
    films_df[list(films_df)[9]].append(v.characters)
    films_df[list(films_df)[10]].append(v.planets)
    films_df[list(films_df)[11]].append(v.url)
    films_df[list(films_df)[12]].append(v.created)
    films_df[list(films_df)[13]].append(v.edited)

#convert to dataframe
films_df = pd.DataFrame.from_dict(films_df)

#check output
films_df.head()

,title,episode_id,opening_crawl,director,producer,release_date,species,starships,vehicles,characters,planets,url,created,edited
0,A New Hope,4,It is a period of civil war.\r\nRebel spaceshi...,George Lucas,"Gary Kurtz, Rick McCallum",1977-05-25,"[http://swapi.dev/api/species/1/, http://swapi...","[http://swapi.dev/api/starships/2/, http://swa...","[http://swapi.dev/api/vehicles/4/, http://swap...","[http://swapi.dev/api/people/1/, http://swapi....","[http://swapi.dev/api/planets/1/, http://swapi...",http://swapi.dev/api/films/1/,2014-12-10T14:23:31.880000Z,2014-12-20T19:49:45.256000Z
1,The Empire Strikes Back,5,It is a dark time for the\r\nRebellion. Althou...,Irvin Kershner,"Gary Kurtz, Rick McCallum",1980-05-17,"[http://swapi.dev/api/species/1/, http://swapi...","[http://swapi.dev/api/starships/3/, http://swa...","[http://swapi.dev/api/vehicles/8/, http://swap...","[http://swapi.dev/api/people/1/, http://swapi....","[http://swapi.dev/api/planets/4/, http://swapi...",http://swapi.dev/api/films/2/,2014-12-12T11:26:24.656000Z,2014-12-15T13:07:53.386000Z
2,Return of the Jedi,6,Luke Skywalker has returned to\r\nhis home pla...,Richard Marquand,"Howard G. Kazanjian, George Lucas, Rick McCallum",1983-05-25,"[http://swapi.dev/api/species/1/, http://swapi...","[http://swapi.dev/api/starships/2/, http://swa...","[http://swapi.dev/api/vehicles/8/, http://swap...","[http://swapi.dev/api/people/1/, http://swapi....","[http://swapi.dev/api/planets/1/, http://swapi...",http://swapi.dev/api/films/3/,2014-12-18T10:39:33.255000Z,2014-12-20T09:48:37.462000Z
3,The Phantom Menace,1,Turmoil has engulfed the\r\nGalactic Republic....,George Lucas,Rick McCallum,1999-05-19,"[http://swapi.dev/api/species/1/, http://swapi...","[http://swapi.dev/api/starships/31/, http://sw...","[http://swapi.dev/api/vehicles/33/, http://swa...","[http://swapi.dev/api/people/2/, http://swapi....","[http://swapi.dev/api/planets/1/, http://swapi...",http://swapi.dev/api/films/4/,2014-12-19T16:52:55.740000Z,2014-12-20T10:54:07.216000Z
4,Attack of the Clones,2,There is unrest in the Galactic\r\nSenate. Sev...,George Lucas,Rick McCallum,2002-05-16,"[http://swapi.dev/api/species/1/, http://swapi...","[http://swapi.dev/api/starships/21/, http://sw...","[http://swapi.dev/api/vehicles/4/, http://swap...","[http://swapi.dev/api/people/2/, http://swapi....","[http://swapi.dev/api/planets/1/, http://swapi...",http://swapi.dev/api/films/5/,2014-12-20T10:57:57.886000Z,2014-12-20T20:18:48.516000Z

## Get people

In [11]:
#get all people from swapi
people = swapi.get_all("people")

#empty dictionary to store values
people_df = {"name": [],
            "height": [],
            "mass": [],
            "hair_color": [],
            "skin_color": [],
            "eye_color": [],
            "birth_year": [],
            "gender": [],
            "homeworld": [],
            "films": [],
            "species": [],
            "vehicles": [],
            "starships": [],
            "created": [],
            "edited": [],
            "url": []   
            }

#get data and store in dictionary
for v in people.iter():
    people_df[list(people_df)[0]].append(v.name)
    people_df[list(people_df)[1]].append(v.height)
    people_df[list(people_df)[2]].append(v.mass)
    people_df[list(people_df)[3]].append(v.hair_color)
    people_df[list(people_df)[4]].append(v.skin_color)
    people_df[list(people_df)[5]].append(v.eye_color)
    people_df[list(people_df)[6]].append(v.birth_year)
    people_df[list(people_df)[7]].append(v.gender)
    people_df[list(people_df)[8]].append(v.homeworld)
    people_df[list(people_df)[9]].append(v.films)
    people_df[list(people_df)[10]].append(v.species)
    people_df[list(people_df)[11]].append(v.vehicles)
    people_df[list(people_df)[12]].append(v.starships)
    people_df[list(people_df)[13]].append(v.created)
    people_df[list(people_df)[14]].append(v.edited)
    people_df[list(people_df)[15]].append(v.url)

    
#convert to dataframe
people_df = pd.DataFrame.from_dict(people_df)

#check output
people_df.head()

,name,height,mass,hair_color,skin_color,eye_color,birth_year,gender,homeworld,films,species,vehicles,starships,created,edited,url
0,Luke Skywalker,172,77,blond,fair,blue,19BBY,male,http://swapi.dev/api/planets/1/,"[http://swapi.dev/api/films/1/, http://swapi.d...",[],"[http://swapi.dev/api/vehicles/14/, http://swa...","[http://swapi.dev/api/starships/12/, http://sw...",2014-12-09T13:50:51.644000Z,2014-12-20T21:17:56.891000Z,http://swapi.dev/api/people/1/
1,C-3PO,167,75,n/a,gold,yellow,112BBY,n/a,http://swapi.dev/api/planets/1/,"[http://swapi.dev/api/films/1/, http://swapi.d...",[http://swapi.dev/api/species/2/],[],[],2014-12-10T15:10:51.357000Z,2014-12-20T21:17:50.309000Z,http://swapi.dev/api/people/2/
2,R2-D2,96,32,n/a,"white, blue",red,33BBY,n/a,http://swapi.dev/api/planets/8/,"[http://swapi.dev/api/films/1/, http://swapi.d...",[http://swapi.dev/api/species/2/],[],[],2014-12-10T15:11:50.376000Z,2014-12-20T21:17:50.311000Z,http://swapi.dev/api/people/3/
3,Darth Vader,202,136,none,white,yellow,41.9BBY,male,http://swapi.dev/api/planets/1/,"[http://swapi.dev/api/films/1/, http://swapi.d...",[],[],[http://swapi.dev/api/starships/13/],2014-12-10T15:18:20.704000Z,2014-12-20T21:17:50.313000Z,http://swapi.dev/api/people/4/
4,Leia Organa,150,49,brown,light,brown,19BBY,female,http://swapi.dev/api/planets/2/,"[http://swapi.dev/api/films/1/, http://swapi.d...",[],[http://swapi.dev/api/vehicles/30/],[],2014-12-10T15:20:09.791000Z,2014-12-20T21:17:50.315000Z,http://swapi.dev/api/people/5/


## Starships

In [15]:
starship = swapi.get_all("starships")

starship_df = {"name":[],
            "model": [],
            "manufacturer": [],
            "cost_in_credits": [],
            "length": [],
            "max_atmosphering_speed": [],
            "crew": [],
            "passengers": [],
            "cargo_capacity": [],
            "consumables": [],
            "hyperdrive_rating": [],
            "MGLT": [],
            "starship_class": [],
            "pilots": [],
            "films": [],
            "created": [],
            "edited": [],
            "url": []   
            }

#get data and store in dictionary
for v in starship.iter():
    starship_df[list(starship_df)[0]].append(v.name)
    starship_df[list(starship_df)[1]].append(v.model)
    starship_df[list(starship_df)[2]].append(v.manufacturer)
    starship_df[list(starship_df)[3]].append(v.cost_in_credits)
    starship_df[list(starship_df)[4]].append(v.length)
    starship_df[list(starship_df)[5]].append(v.max_atmosphering_speed)
    starship_df[list(starship_df)[6]].append(v.crew)
    starship_df[list(starship_df)[7]].append(v.passengers)
    starship_df[list(starship_df)[8]].append(v.cargo_capacity)
    starship_df[list(starship_df)[9]].append(v.consumables)
    starship_df[list(starship_df)[10]].append(v.hyperdrive_rating)
    starship_df[list(starship_df)[11]].append(v.MGLT)
    starship_df[list(starship_df)[12]].append(v.starship_class)
    starship_df[list(starship_df)[13]].append(v.pilots)
    starship_df[list(starship_df)[14]].append(v.films)
    starship_df[list(starship_df)[15]].append(v.created)
    starship_df[list(starship_df)[16]].append(v.edited)
    starship_df[list(starship_df)[17]].append(v.url)

    
#convert to dataframe
starship_df = pd.DataFrame.from_dict(starship_df)

#check output
starship_df.head()

,name,model,manufacturer,cost_in_credits,length,max_atmosphering_speed,crew,passengers,cargo_capacity,consumables,hyperdrive_rating,MGLT,starship_class,pilots,films,created,edited,url
0,CR90 corvette,CR90 corvette,Corellian Engineering Corporation,3500000,150,950,30-165,600,3000000,1 year,2.0,60,corvette,[],"[http://swapi.dev/api/films/1/, http://swapi.d...",2014-12-10T14:20:33.369000Z,2014-12-20T21:23:49.867000Z,http://swapi.dev/api/starships/2/
1,Star Destroyer,Imperial I-class Star Destroyer,Kuat Drive Yards,150000000,"1,600",975,"47,060",n/a,36000000,2 years,2.0,60,Star Destroyer,[],"[http://swapi.dev/api/films/1/, http://swapi.d...",2014-12-10T15:08:19.848000Z,2014-12-20T21:23:49.870000Z,http://swapi.dev/api/starships/3/
2,Sentinel-class landing craft,Sentinel-class landing craft,"Sienar Fleet Systems, Cyngus Spaceworks",240000,38,1000,5,75,180000,1 month,1.0,70,landing craft,[],[http://swapi.dev/api/films/1/],2014-12-10T15:48:00.586000Z,2014-12-20T21:23:49.873000Z,http://swapi.dev/api/starships/5/
3,Death Star,DS-1 Orbital Battle Station,"Imperial Department of Military Research, Sien...",1000000000000,120000,n/a,"342,953","843,342",1000000000000,3 years,4.0,10,Deep Space Mobile Battlestation,[],[http://swapi.dev/api/films/1/],2014-12-10T16:36:50.509000Z,2014-12-20T21:26:24.783000Z,http://swapi.dev/api/starships/9/
4,Millennium Falcon,YT-1300 light freighter,Corellian Engineering Corporation,100000,34.37,1050,4,6,100000,2 months,0.5,75,Light freighter,"[http://swapi.dev/api/people/13/, http://swapi...","[http://swapi.dev/api/films/1/, http://swapi.d...",2014-12-10T16:59:45.094000Z,2014-12-20T21:23:49.880000Z,http://swapi.dev/api/starships/10/

## Planets

In [22]:
planets = swapi.get_all("planets")

planet_df = {"name": [],
            "rotation_period": [],
            "orbital_period": [],
            "diameter": [],
            "climate": [],
            "gravity": [],
            "terrain": [],
            "surface_water": [],
            "population": [],
            "residents": [],
            "films":[],
            "created": [],
            "edited": [],
            "url": []   
            }

#get data and store in dictionary
for v in planets.iter():
    planet_df[list(planet_df)[0]].append(v.name)
    planet_df[list(planet_df)[1]].append(v.rotation_period)
    planet_df[list(planet_df)[2]].append(v.orbital_period)
    planet_df[list(planet_df)[3]].append(v.diameter)
    planet_df[list(planet_df)[4]].append(v.climate)
    planet_df[list(planet_df)[5]].append(v.gravity)
    planet_df[list(planet_df)[6]].append(v.terrain)
    planet_df[list(planet_df)[7]].append(v.surface_water)
    planet_df[list(planet_df)[8]].append(v.population)
    planet_df[list(planet_df)[9]].append(v.residents)
    planet_df[list(planet_df)[10]].append(v.films)
    planet_df[list(planet_df)[11]].append(v.created)
    planet_df[list(planet_df)[12]].append(v.edited)
    planet_df[list(planet_df)[13]].append(v.url)

    
#convert to dataframe
planet_df = pd.DataFrame.from_dict(planet_df)

#check output
planet_df.head()

,name,rotation_period,orbital_period,diameter,climate,gravity,terrain,surface_water,population,residents,films,created,edited,url
0,Tatooine,23,304,10465,arid,1 standard,desert,1,200000,"[http://swapi.dev/api/people/1/, http://swapi....","[http://swapi.dev/api/films/1/, http://swapi.d...",2014-12-09T13:50:49.641000Z,2014-12-20T20:58:18.411000Z,http://swapi.dev/api/planets/1/
1,Alderaan,24,364,12500,temperate,1 standard,"grasslands, mountains",40,2000000000,"[http://swapi.dev/api/people/5/, http://swapi....","[http://swapi.dev/api/films/1/, http://swapi.d...",2014-12-10T11:35:48.479000Z,2014-12-20T20:58:18.420000Z,http://swapi.dev/api/planets/2/
2,Yavin IV,24,4818,10200,"temperate, tropical",1 standard,"jungle, rainforests",8,1000,[],[http://swapi.dev/api/films/1/],2014-12-10T11:37:19.144000Z,2014-12-20T20:58:18.421000Z,http://swapi.dev/api/planets/3/
3,Hoth,23,549,7200,frozen,1.1 standard,"tundra, ice caves, mountain ranges",100,unknown,[],[http://swapi.dev/api/films/2/],2014-12-10T11:39:13.934000Z,2014-12-20T20:58:18.423000Z,http://swapi.dev/api/planets/4/
4,Dagobah,23,341,8900,murky,N/A,"swamp, jungles",8,unknown,[],"[http://swapi.dev/api/films/2/, http://swapi.d...",2014-12-10T11:42:22.590000Z,2014-12-20T20:58:18.425000Z,http://swapi.dev/api/planets/5/

## Species

In [23]:
species = swapi.get_all("species")

species_df = {"name": [],
            "classification": [],
            "designation": [],
            "average_height": [],
            "skin_colors": [],
            "hair_colors": [],
            "eye_colors": [],
            "average_lifespan": [],
            "homeworld": [],
            "language": [],
            "people": [],
            "films":[],
            "created": [],
            "edited": [],
            "url": []   
            }

#get data and store in dictionary
for v in species.iter():
    species_df[list(species_df)[0]].append(v.name)
    species_df[list(species_df)[1]].append(v.classification)
    species_df[list(species_df)[2]].append(v.designation)
    species_df[list(species_df)[3]].append(v.average_height)
    species_df[list(species_df)[4]].append(v.skin_colors)
    species_df[list(species_df)[5]].append(v.hair_colors)
    species_df[list(species_df)[6]].append(v.eye_colors)
    species_df[list(species_df)[7]].append(v.average_lifespan)
    species_df[list(species_df)[8]].append(v.homeworld)
    species_df[list(species_df)[9]].append(v.language)
    species_df[list(species_df)[10]].append(v.people)
    species_df[list(species_df)[11]].append(v.films)
    species_df[list(species_df)[12]].append(v.created)
    species_df[list(species_df)[13]].append(v.edited)
    species_df[list(species_df)[14]].append(v.url)

    
#convert to dataframe
species_df = pd.DataFrame.from_dict(species_df)

#check output
species_df.head()

,name,classification,designation,average_height,skin_colors,hair_colors,eye_colors,average_lifespan,homeworld,language,people,films,created,edited,url
0,Human,mammal,sentient,180,"caucasian, black, asian, hispanic","blonde, brown, black, red","brown, blue, green, hazel, grey, amber",120,http://swapi.dev/api/planets/9/,Galactic Basic,"[http://swapi.dev/api/people/66/, http://swapi...","[http://swapi.dev/api/films/1/, http://swapi.d...",2014-12-10T13:52:11.567000Z,2014-12-20T21:36:42.136000Z,http://swapi.dev/api/species/1/
1,Droid,artificial,sentient,n/a,n/a,n/a,n/a,indefinite,None,n/a,"[http://swapi.dev/api/people/2/, http://swapi....","[http://swapi.dev/api/films/1/, http://swapi.d...",2014-12-10T15:16:16.259000Z,2014-12-20T21:36:42.139000Z,http://swapi.dev/api/species/2/
2,Wookie,mammal,sentient,210,gray,"black, brown","blue, green, yellow, brown, golden, red",400,http://swapi.dev/api/planets/14/,Shyriiwook,"[http://swapi.dev/api/people/13/, http://swapi...","[http://swapi.dev/api/films/1/, http://swapi.d...",2014-12-10T16:44:31.486000Z,2014-12-20T21:36:42.142000Z,http://swapi.dev/api/species/3/
3,Rodian,sentient,reptilian,170,"green, blue",n/a,black,unknown,http://swapi.dev/api/planets/23/,Galatic Basic,[http://swapi.dev/api/people/15/],[http://swapi.dev/api/films/1/],2014-12-10T17:05:26.471000Z,2014-12-20T21:36:42.144000Z,http://swapi.dev/api/species/4/
4,Hutt,gastropod,sentient,300,"green, brown, tan",n/a,"yellow, red",1000,http://swapi.dev/api/planets/24/,Huttese,[http://swapi.dev/api/people/16/],"[http://swapi.dev/api/films/1/, http://swapi.d...",2014-12-10T17:12:50.410000Z,2014-12-20T21:36:42.146000Z,http://swapi.dev/api/species/5/

## Vehicles

In [29]:
vehicles = swapi.get_all("vehicles")

vehicles_df = {"name": [],
            "model": [],
            "manufacturer": [],
            "cost_in_credits": [],
            "length": [],
            "max_atmosphering_speed": [],
            "crew": [],
            "passengers": [],
            "cargo_capacity": [],
            "consumables": [],
            "vehicle_class": [],
            "pilots": [],
            "films":[],
            "created": [],
            "edited": [],
            "url": []   
            }         
   
#get data and store in dictionary
for v in vehicles.iter():
    vehicles_df[list(vehicles_df)[0]].append(v.name)
    vehicles_df[list(vehicles_df)[1]].append(v.model)
    vehicles_df[list(vehicles_df)[2]].append(v.manufacturer)
    vehicles_df[list(vehicles_df)[3]].append(v.cost_in_credits)
    vehicles_df[list(vehicles_df)[4]].append(v.length)
    vehicles_df[list(vehicles_df)[5]].append(v.max_atmosphering_speed)
    vehicles_df[list(vehicles_df)[6]].append(v.crew)
    vehicles_df[list(vehicles_df)[7]].append(v.passengers)
    vehicles_df[list(vehicles_df)[8]].append(v.cargo_capacity)
    vehicles_df[list(vehicles_df)[9]].append(v.consumables)
    vehicles_df[list(vehicles_df)[10]].append(v.vehicle_class)
    vehicles_df[list(vehicles_df)[11]].append(v.pilots)
    vehicles_df[list(vehicles_df)[12]].append(v.films)
    vehicles_df[list(vehicles_df)[13]].append(v.created)
    vehicles_df[list(vehicles_df)[14]].append(v.edited)
    vehicles_df[list(vehicles_df)[15]].append(v.url)

    
#convert to dataframe
vehicles_df = pd.DataFrame.from_dict(vehicles_df)

#check output
vehicles_df.head()

,name,model,manufacturer,cost_in_credits,length,max_atmosphering_speed,crew,passengers,cargo_capacity,consumables,vehicle_class,pilots,films,created,edited,url
0,Sand Crawler,Digger Crawler,Corellia Mining Corporation,150000,36.8,30,46,30,50000,2 months,wheeled,[],"[http://swapi.dev/api/films/1/, http://swapi.d...",2014-12-10T15:36:25.724000Z,2014-12-20T21:30:21.661000Z,http://swapi.dev/api/vehicles/4/
1,T-16 skyhopper,T-16 skyhopper,Incom Corporation,14500,10.4,1200,1,1,50,0,repulsorcraft,[],[http://swapi.dev/api/films/1/],2014-12-10T16:01:52.434000Z,2014-12-20T21:30:21.665000Z,http://swapi.dev/api/vehicles/6/
2,X-34 landspeeder,X-34 landspeeder,SoroSuub Corporation,10550,3.4,250,1,1,5,unknown,repulsorcraft,[],[http://swapi.dev/api/films/1/],2014-12-10T16:13:52.586000Z,2014-12-20T21:30:21.668000Z,http://swapi.dev/api/vehicles/7/
3,TIE/LN starfighter,Twin Ion Engine/Ln Starfighter,Sienar Fleet Systems,unknown,6.4,1200,1,0,65,2 days,starfighter,[],"[http://swapi.dev/api/films/1/, http://swapi.d...",2014-12-10T16:33:52.860000Z,2014-12-20T21:30:21.670000Z,http://swapi.dev/api/vehicles/8/
4,Snowspeeder,t-47 airspeeder,Incom corporation,unknown,4.5,650,2,0,10,none,airspeeder,"[http://swapi.dev/api/people/1/, http://swapi....",[http://swapi.dev/api/films/2/],2014-12-15T12:22:12Z,2014-12-20T21:30:21.672000Z,http://swapi.dev/api/vehicles/14/

## Save outputs

In [33]:
people_df.to_csv(".\\data\\scraped\\people.csv", index=False)
starship_df.to_csv(".\\\data\\scraped\\starships.csv", index=False)
planet_df.to_csv(".\\\data\\scraped\\planets.csv", index=False)
species_df.to_csv(".\\\data\\scraped\\species.csv", index=False)
films_df.to_csv(".\\\data\\scraped\\films.csv", index=False)
vehicles_df.to_csv(".\\data\\scraped\\vehicles.csv", index=False)